export const CHANGE_TO_LOGGED = 'CHANGE_TO_LOGGED'

export const CHANGE_TO_LOADING = 'CHANGE_TO_LOADING'
export const CHANGE_TO_LOADED = 'CHANGE_TO_LOADED'

export const SHOW_LOGIN_PAGE = 'SHOW_LOGIN_PAGE'
export const HIDE_LOGIN_PAGE = 'HIDE_LOGIN_PAGE'

export const USER_COLLECTS = 'USER_COLLECTS'

